### ISSUE TITLE
Fine Tune internship creation endpoint

### ISSUE THREAD

**Issue by LiFaytheGoblin** [imimap/imimap21#163]
Example: if one finds a company with name "HTW Berlin" that company is saved as this internships company. it might however be that one needs to specify the branch later on. that is not currently possible except if the different branch name is given in the internship creation endpoint right away. otherwise one will edit the other company later on, which is not what we want.

So: upon internship creation, get suggestions for possible companies the student might mean
The student can now chose an existing company or create a new one

**Comment by JuliaZamaitat** [comment]
wird in #299  bearbeitet
