### ISSUE TITLE
company erstellen funktioniert nicht

### ISSUE THREAD

**Issue by LiFaytheGoblin** [imimap/imimap21#166]
I get an error when trying to create the company, something with the Google API:
""REQUEST_DENIED. Could not get coordinates for Wilhelminenhofstraße 75A 12459 Berlin Germany""

Here's my test:
curl --location --request POST 'http://localhost:9000/api/companies/?companyName=HTW%20Berlin&branchName=Fachbereich%204&street=Wilhelminenhofstra%C3%9Fe&streetNumber=75A&zip=12459&city=Berlin&country=Germany' \ --header 'Authorization: Bearer THEBEARERTOKEN'

Documentation: https://www.getpostman.com/collections/3406cd53e9316e2cf003

**Comment by Kaes3kuch3n** [comment]
Fixed in 7b062ebd8c9614be1993f280ea52ad110b74153d
