### ISSUE TITLE
Warning: phantomjs is deprecated

### ISSUE THREAD

**Issue by LiFaytheGoblin** [imimap/imimap21#185]
![image](https://user-images.githubusercontent.com/5471273/125740353-7a12b595-2c78-4836-a1c4-ecf5ff059844.png)

appears when building

**Comment by Kaes3kuch3n** [comment]
I know :( Aber es funktioniert noch perfectly fine, von daher ist's denke ich erstmal okay

**Comment by LiFaytheGoblin** [comment]
Hier sollten wir nochmal gucken vor dem release denke ich?
