### ISSUE TITLE
Profs sollen nicht automatisch Admins sein

### ISSUE THREAD

**Issue by LiFaytheGoblin** [imimap/imimap21#210]
oder müssen wir das einschränken und die admin rechte anders als über die instructor rolle vergeben?

**Comment by LiFaytheGoblin** [comment]
@JuliaZamaitat das ist noch ne offene frage

**Comment by JuliaZamaitat** [comment]
@Kaes3kuch3n Wie markiert man überhaupt im Moment, wer Admin ist und wer nicht, wenn sich ganz normal eingeloggt wird mit den HRZ Daten? Ich zb muss ja auch eine Admin-Rolle bekommen...

**Comment by Kaes3kuch3n** [comment]
@JuliaZamaitat Benutzt Du dafür Deinen s0-Account oder hast Du dafür einen Extra-HTW-Mitarbeitenden-Account?

**Comment by JuliaZamaitat** [comment]
@Kaes3kuch3n Ich hab dafür meinen s0-Account benutzt bisher!

**Comment by Kaes3kuch3n** [comment]
Okay, weil aktuell basiert die Admin-Rolle einfach auf der Rolle, die wir vom LDAP bekommen:
- GP-F4-IMI-B-PROF = Admin
- GP-F4-IMI-B-STUD = Student (bzw. alles andere ebenfalls)

Dann bräuchten wir noch ne Option, um andere User auch zu Admins machen zu können.

Und vielleicht sollten wir auch noch filtern, sodass sich nur User mit der IMI-Rolle einloggen können
