### ISSUE TITLE
Praktikumsdauer soll ausgerechnet werden statt hardgecoded sein 

### ISSUE THREAD

**Issue by LiFaytheGoblin** [imimap/imimap21#213]
in der studi sicht auf eigene praktika hab ich gerade gesehen dass da stand lang genug 13 wochen bei beiden teilpraktika obwohl ein praktikum nur 8 wochen lang war. vermutl sind 13 wochen beide zusammen? 

- [x] es soll klar sein wann welche dauer gemeint ist. bei praktika ist es relevant dass sie mind. 8 wochen lang sind. bei dem modul müssen insg 16 wochen zusammen kommen.
- [x] der praktikumsstart und ende soll menschen-leslich angezeigt werden statt als timestamp

**Comment by JuliaZamaitat** [comment]
- [x] in jedem Formular soll das Start und Enddatum richtig angezeigt werden
