### ISSUE TITLE
Admin UI: Quick actions should not be displayed if no internship is available

### ISSUE THREAD

**Issue by LiFaytheGoblin** [imimap/imimap21#232]

**Comment by JuliaZamaitat** [comment]
![image](https://user-images.githubusercontent.com/33123853/151181755-2182717e-12bc-4ff4-8067-6e7fb8b9966a.png)

**Comment by Kaes3kuch3n** [comment]
@JuliaZamaitat Ist hier der Button "AEP bestanden markieren" gemeint? Weil Suchanfragen zurücksetzen und Details bearbeiten sind ja trotzdem sinnvoll, auch wenn es kein Teilpraktikum gibt
