### ISSUE TITLE
Anzahl Suchanfragen transparent anzeigen

### ISSUE THREAD

**Issue by LiFaytheGoblin** [imimap/imimap21#236]
* kontingent auf suchergebnisseite für studis anzeigen
* und für admins, je studi das verbliebene kontingent anzeigen o.ä. damit klar ist, ob das zurücksetzen funktioniert hat

**Comment by LiFaytheGoblin** [comment]
man sollte nochmal über das limit nachdenken: wofür gibt es welche limits? evtl modell anpassen!

**Comment by JuliaZamaitat** [comment]
![image](https://user-images.githubusercontent.com/33123853/151184058-be064a8d-cd5a-42b4-9890-20dbb81c876e.png)

**Comment by JuliaZamaitat** [comment]
Ich denke es ergibt Sinn, nur ein Limit für Companies einzuführen – also man kann maximal 12 Companies sehen, wenn sagen wir 15 Praktika bei den 12 Companies waren, macht es nichts, die 3 Praktika mehr zu sehen. Andersrum wäre es schwierig, wenn man nur 12 Praktika sehen darf, aber 5 davon bei Fraunhofer waren – dann hat man nur 7 gute Suchergebnisse für sich.

Deshalb Vorschlag meinerseits: InternshipsSeen zu CompaniesSeen ändern, Limit überall einbauen, eventuell auch beim Vorschlag bei Neuanlage eines Praktikums wenn man Praktikumsnamen eingibt.

Ich weiß auch ehrlich gesagt nicht mehr was Company Suggest war, auch aus dem alten Code nicht erschließbar.

@Kaes3kuch3n was denkst du?

**Comment by Kaes3kuch3n** [comment]
Ja, klingt sinnvoll, finde ich.

Am schönsten fände ich es, wenn verschiedene Branches von einer Company noch als eine Company zählen, aber das könnten wir der Einfachheit halber auch erstmal ignorieren, denke ich.
