### ISSUE TITLE
Query Internships Endpoint

### ISSUE THREAD

**Issue by Kaes3kuch3n** [imimap/imimap21#33]
API endpoint for querying past internships of other students. Should return at most `12 - n` internships (n = number of previously found internships for current user). Should send confirmation request first if there are more than 6 results for the given filter parameters.

**Filters:**
- [ ] Paid/unpaid
- [ ] Location
- [ ] Area of work
- [ ] Programming language

**Comment by LiFaytheGoblin** [comment]
still missing: 
- confirmation request
- returning random set of internships out of all results
- options filter is not working
