### ISSUE TITLE
Get Previously Found Internships Endpoint

### ISSUE THREAD

**Issue by Kaes3kuch3n** [imimap/imimap21#35]
Should return a list of all previously found internships (up to 12) for the current user.

**Comment by LiFaytheGoblin** [comment]
ist das dasselbe wie #30

**Comment by Kaes3kuch3n** [comment]
> ist das dasselbe wie #30

Nee, das hier ist der Endpoint, das andere ist das UI im Frontend :)

**Comment by LiFaytheGoblin** [comment]
@RobinUndersigned wie war das nochmal? wir brauchen den endpoint oder?
