### ISSUE TITLE
Register IMI-Map SP with HRZ IP

### ISSUE THREAD

**Issue by Kaes3kuch3n** [imimap/imimap21#48]
Register the IMI-Map as Service Provider with the HTW Hochschulrechenzentrum's Identity Provider for Single-Sign-On.

See also [relevant comment on #19](https://github.com/imimap/imimap21/issues/19#issuecomment-830704524)

**Comment by LiFaytheGoblin** [comment]
@JuliaZamaitat bin mir nicht sicher was es hiermit auf sich hat. Denke es wäre ein switch von LDAP weg. was denkst du, hat keine prio oder?

**Comment by Kaes3kuch3n** [comment]
@LiFaytheGoblin Ja, das war das Login über das HRZ-SSO/Shibboleth/SAML anstatt über LDAP, aber da kam ja keine Rückmeldung mehr vom HRZ
