### ISSUE TITLE
Add New Internship Part View

### ISSUE THREAD

**Issue by Kaes3kuch3n** [imimap/imimap21#53]
Should create a new internship part for the student in the specified semester.

**View:**
![Screenshot 2021-05-18 at 19 23 42](https://user-images.githubusercontent.com/8218240/118697750-eae79d80-b80f-11eb-9b82-d632b9614228.png)
**Result:**
![Screenshot 2021-05-18 at 19 24 03](https://user-images.githubusercontent.com/8218240/118697765-ede28e00-b80f-11eb-90d2-07a7a88f0989.png)

**Comment by LiFaytheGoblin** [comment]
Improvements: 
- Refactor so that components can be re-used in EditInternship

- Get company sizes from API instead of hard coding them

**Comment by LiFaytheGoblin** [comment]
Wir hatten das ja in der jetzigen IMI Map version etwas verändert. @JuliaZamaitat was denkst du fehlt noch? Soll noch etwas am "neues Praktikum anlegen" feature verändert werden?
