### ISSUE TITLE
Select An Existing Company For Internship Part View

### ISSUE THREAD

**Issue by Kaes3kuch3n** [imimap/imimap21#54]
Should allow the user to:
- [ ] search for their internship company in the system
- [ ] see a list of search results
- [ ] select a company from the list of search results
- [ ] view the company details before saving their selection

**Search view:**
![Screenshot 2021-05-18 at 19 25 44](https://user-images.githubusercontent.com/8218240/118698367-98f34780-b810-11eb-92e2-e854b435a3d6.png)
**Search results:**
![Screenshot 2021-05-18 at 19 26 26](https://user-images.githubusercontent.com/8218240/118698425-a9a3bd80-b810-11eb-97cf-1b5c6ef1e89f.png)
**No results:**
![Screenshot 2021-05-18 at 19 26 03](https://user-images.githubusercontent.com/8218240/118698449-b2948f00-b810-11eb-8ea5-541e19af083e.png)
**View company:**
![Screenshot 2021-05-18 at 19 26 51](https://user-images.githubusercontent.com/8218240/118698780-17e88000-b811-11eb-9652-b01f06b81b63.png)

**Comment by JuliaZamaitat** [comment]
wird im PR #299 bearbeitet
