### ISSUE TITLE
Upload PDF File Endpoint

### ISSUE THREAD

**Issue by Kaes3kuch3n** [imimap/imimap21#63]
Should accept a PDF file upload, a file type (contract, report, ...) and an internship part ID. Should add the uploaded file to the internship part as the specified file type.

**Comment by LiFaytheGoblin** [comment]
geht bei der praktikumsbeantragung wenn man "praktikumsantrag hochladen" klickt. da kommt zumindest submitted. 
- schauen, in wiefern da echt ein pdf hochgeladen wird
- kopieren für die anderen dokumente

**Comment by Kaes3kuch3n** [comment]
Ist bereits implementiert
