### ISSUE TITLE
Get All Internship Locations For Semester Endpoint

### ISSUE THREAD

**Issue by Kaes3kuch3n** [imimap/imimap21#89]
Should return a list of locations of the internships for a specific semester. Should take a semester as parameter.

**Comment by LiFaytheGoblin** [comment]
Stand: es werden die kompletten internships returned, nicht nur die locations. ok so?

**Comment by Kaes3kuch3n** [comment]
> Stand: es werden die kompletten internships returned, nicht nur die locations. ok so?

@LiFaytheGoblin Für die Suche ja, aber für die Karte brauchen wir noch nen Endpoint, der alle Internships eines Semesters zurückgibt, aber nur deren Locations, damit man nicht alle Details im Frontend auslesen kann
